### ISSUE TITLE
Doesn't work if client has got  two-factor authentication

### ISSUE THREAD

**Issue by FogelAO** [geniushkg/github-oauth#4]
Hey,
I'm having an issue with two-factor authorization, 

Here is stacktrace:

FATAL EXCEPTION: main
Process: fogelao.com.github.gitauthtest, PID: 14878
java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
	at com.hardikgoswami.oauthLibGithub.OauthActivity$1.shouldOverrideUrlLoading(OauthActivity.java:87)
	at com.android.webview.chromium.WebViewContentsClientAdapter.shouldOverrideUrlLoading(WebViewContentsClientAdapter.java:356)
	at org.chromium.android_webview.AwContentsClient.shouldIgnoreNavigation(AwContentsClient.java:168)
	at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:269)
	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:41)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5527)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)

Hope you will fix it, Thanks!

**Comment by geniushkg** [comment]
Hello @FogelAO  , thanks for reporting , i was not aware of 2FA mechanism, I think they introduced recently.

You can expect an update by this weekend.

**Comment by geniushkg** [comment]
@FogelAO, if possible please share code, what changes you made to accommodate 2fa.
